### ISSUE TITLE
ModuleNotFoundError: No module named 'youtube_dl'

### ISSUE THREAD

**Issue by z0mn** [nbr23/ydl-podcast#1]
Hi! I have Python 2.7 and Python 3 installed in Ubuntu 16.04. I have installed youtube-dl using: `pip3 install youtube_dl` but receive the following message when executing `ydl_podcast.py`: 

```Traceback (most recent call last):
  File "ydl_podcast.py", line 11, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
```

I've uninstalled and reinstalled youtube-dl using both pip and pip3, but still run into this message. Thanks for the script, and help!

**Comment by nbr23** [comment]
Hi @z0mn, that's interesting, it should work with pip3. Can you confirm if youtube-dl is properly installed and which version you have (`youtube-dl --version`) ?
I will try to reproduce the issue on my end with an Ubuntu 16.04.

**Comment by nbr23** [comment]
I just tried on an Ubuntu 16.04 container, running:
```
pip3 install --upgrade pip # because it seems the shipped version of pip is outdated by quite a lot
pip install youtube_dl
```
And it went through well. I'd say try upgrading pip and then installing youtube_dl again. If you could share the outputs when you try this it might help.

Thanks!

**Comment by z0mn** [comment]
Hey! Okay, so here's what I've got:
**youtube-dl**
``` 
(1:3952)# youtube-dl --version
2020.06.06 
```

**pip**
```
(1:3953)# pip3 install --upgrade pip
/usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages/pip-20.2b1-py2.7.egg (20.2b1)
```

**youtube_dl install**
```
(1:3954)# pip install youtube_dl
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: youtube_dl in /usr/local/lib/python2.7/dist-packages (2020.6.6)
```

**Running ydl_podcast.py**
Python:
```
(1:3957)# python ydl_podcast.py
Traceback (most recent call last):
  File "ydl_podcast.py", line 6, in <module>
    import html
ImportError: No module named html
```
Python3:
```
(1:3958)# python3 ydl_podcast.py
Traceback (most recent call last):
  File "ydl_podcast.py", line 11, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
```

**Comment by z0mn** [comment]
Solved: I used `> easy_install youtube_dl` - it installed youtube_dl, then the script ran fine!

**Comment by nbr23** [comment]
Ah nice. It's strange, your pip3 seems to be using python2.7 which doesn't make much sense (you can verify with `pip3 -V`). Glad you found a solution though :)
