### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by wangfeng35** [nbr23/ydl-podcast#15]
I got this error:

`Traceback (most recent call last):
  File "/usr/local/bin/ydl-podcast", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ydl_podcast/__main__.py", line 56, in main
    download(ydl_mod, sub)
  File "/usr/local/lib/python3.11/dist-packages/ydl_podcast/__init__.py", line 246, in download
    entry = get_video_metadata(ydl_mod, md["url"], options, quiet=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ydl_podcast/__init__.py", line 152, in get_video_metadata
    return json.loads(output.getvalue().split("\n")[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

The config file is 

`subscriptions:
  - name: lurenqi 
    url: https://space.bilibili.com/573606572/video
    retention_days: 14 # How old is the oldest video to download and keep locally
    initialize: False # Download the whole channel on first run
    download_last: 22 # Only download the last video at each run
    audio_only: True # Extract and keep audio only
    format: m4a      # Force end format
    filename_template: '%(id)s.%(ext)s' # Use this format for files saved from this subscription

output_dir: /root/ydl-podcast/
url_root: https://podcast.example.com
youtube-dl-module: yt-dlp
`

How to solve it, thanks.

**Comment by wangfeng35** [comment]
I found the reason. 

The config of retention_days is set to 14, and config of download_last is set to 5, while there are only two episodes in the last 14 days.  Therefore, the other three info of episodes is empty.
